language: php
php:
  - 5.6
  - 7.0
  - nightly
script:
  - php composer.phar self-update
  - php composer.phar install --dev
  - ./vendor/bin/phpunit
  
after_success:
  - travis_retry php vendor/bin/coveralls
